services:
  couchdb:
    image: docker.io/couchdb:3.5
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - 127.0.0.1:5984:5984
  rest-on-couch:
    build: ./rest-on-couch
    ports:
      - 127.0.0.1:4000:4000
    env_file:
      - .env.test
    depends_on:
      - couchdb
